.travis.yml, package-lock.json, src/components/Input/style.scss, src/validators/email.js, tests/unit/factories/FormBuilder.spec.js
=> Fixed input append and prepend wrapping.

src/components/Button/css/_sizes.scss, src/components/Button/script.js, src/components/Button/style.scss, src/components/Button/template.html, src/components/Loader/css/_sizes.scss, src/components/Loader/css/_variables.scss, src/components/Loader/style.scss
Added loading spinner integration to button component.
=> #76 button loading spinner

src/components/Select/template.html
- Updated select dropdown to have the same size as the select input.
* **What is the current behavior?** (You can also link to an open issue here)
Select dropdown doesn't change in size when setting a select size.
* **What is the new behavior?** (If this is a feature change)
Select dropdown reflects the select input size property.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
=> Updated select dropdown to have the same size as the select input.

src/components/NavItem/template.html, src/components/Pagination/css/_variants.scss, src/components/Pagination/script.js, src/components/Pagination/style.scss, src/components/Pagination/template.html, src/helpers/debounce.js, src/helpers/index.js, src/helpers/off.js, src/helpers/on.js, src/mixins/components/providers/PopupProviderMixin.vue, tests/unit/components/Icon.spec.js, tests/unit/components/Pagination.spec.js, tests/unit/components/__snapshots__/Icon.spec.js.snap, tests/unit/helpers/debounce.spec.js, tests/unit/helpers/getStyleProperty.spec.js, tests/unit/helpers/off.spec.js, tests/unit/helpers/on.spec.js, tests/unit/helpers/once.spec.js, tests/unit/helpers/removeClass.spec.js, tests/unit/helpers/triggerEvent.spec.js, tests/unit/mixins/components/providers/PopupProviderMixin.spec.js
- Responsively changing pagination items limit
- Added missing Icon component tests
- Fixed #78 for router-link component
=> Pagination improvements

package-lock.json, package.json
Provides a funding URL in `package.json`.
=> Added funding URL and updated packages.

package-lock.json, package.json, src/components/DropdownItem/template.html, src/components/InputNumber/script.js, tests/unit/.eslintrc.js, tests/unit/components/Alert.spec.js, tests/unit/components/Collapsible.spec.js, tests/unit/components/Dropdown.spec.js, tests/unit/components/FormError.spec.js, tests/unit/components/Modal.spec.js, tests/unit/components/Select.spec.js, tests/unit/components/Tooltip.spec.js, tests/unit/components/__snapshots__/Dropdown.spec.js.snap, tests/unit/components/__snapshots__/DropdownMenu.spec.js.snap, tests/unit/components/__snapshots__/FormError.spec.js.snap, tests/unit/components/__snapshots__/Modal.spec.js.snap, tests/unit/components/__snapshots__/Popover.spec.js.snap, tests/unit/components/__snapshots__/Select.spec.js.snap, tests/unit/components/__snapshots__/Sidebar.spec.js.snap, tests/unit/components/__snapshots__/Tooltip.spec.js.snap, tests/unit/helpers/getStyleProperty.spec.js, tests/unit/mixins/components/providers/CollapsibleProviderMixin.spec.js, tests/unit/mixins/components/providers/PopupProviderMixin.spec.js, tests/unit/transitions/__snapshots__/TransitionExpand.spec.js.snap
Fixes broken tests after Vue update.
=> Fixed broken tests after Vue update.

package-lock.json, package.json, src/components/BreadcrumbItem/template.html, src/components/Button/template.html, src/components/DropdownItem/index.vue, src/components/DropdownItem/script.js, src/components/DropdownItem/template.html, src/components/Linkable/index.vue, src/components/Linkable/script.js, src/components/Linkable/template.html, src/components/ListGroupItem/index.vue, src/components/ListGroupItem/script.js, src/components/ListGroupItem/template.html, src/components/NavItem/index.vue, src/components/NavItem/template.html, src/components/NavbarBrand/template.html, tests/unit/components/DropdownItem.spec.js, tests/unit/components/Linkable.spec.js, tests/unit/components/__snapshots__/CheckboxButton.spec.js.snap, tests/unit/components/__snapshots__/DropdownItem.spec.js.snap, tests/unit/components/__snapshots__/InputNumber.spec.js.snap, tests/unit/components/__snapshots__/RadioButton.spec.js.snap
Bug fix.
* **What is the current behavior?** (You can also link to an open issue here)
Linkable items are not accepting `@click.native` for non-component elements anymore.
=> #120 linkable improvement

packages/inkline/src/components/Sidebar/css/_variables.scss, packages/inkline/src/components/Sidebar/style.scss, packages/nuxt-module/README.md, packages/vue-cli-plugin/README.md
Bug fix
* **What is the current behavior?** (You can also link to an open issue here)
Sidebar wrapper doesn't have a z-index, causing it to appear underneath some page elements.
* **What is the new behavior?** (If this is a feature change)
Sidebar wrapper now uses the same z-index as `position: fixed` elements.
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
=> Sidebar z index fix

.github/workflows/build-workflow.yml, package.json, packages/nuxt-module/package.json, packages/nuxt-module/tests/app/package-lock.json, packages/vue-cli-plugin/package.json
Bug fix
* **What is the current behavior?** (You can also link to an open issue here)
Installing nuxt-module and vue-cli plugin throw a postinstall error.
=> Fixed module postinstall hook error.

.github/contributing.md, README.md, packages/docs/pages/docs/preface/contribution-guide.md
Readme updates
Some links was broken
Fixed broken links
Trimmed trailing spaces
=> Fix broken links

packages/docs/package-lock.json, packages/docs/pages/docs/forms/validation/schema.md, packages/inkline/src/components/IFormGroup/script.js, packages/inkline/src/components/IFormLabel/style.scss, packages/inkline/tests/components/IFormGroup.spec.js, packages/nuxt-module/package-lock.json, packages/nuxt-module/tests/app/package-lock.json, packages/vue-cli-plugin/package-lock.json
Feature  #102 
Fix vue warn about invalid markup on `/docs/forms/validation/schema` page (error was only in dev mode)
Update inkline to actual version
When some input is required added class-modifier `-required` for `.form-group`
=> Feature: Formgroup required

package-lock.json, package.json, packages/docs/components/docs/Code.vue, packages/docs/package-lock.json, packages/docs/tests/pages/__snapshots__/index.spec.js.snap, packages/inkline/package-lock.json, packages/inkline/package.json, packages/inkline/src/components/IDropdownMenu/script.js, packages/inkline/src/components/IDropdownMenu/template.html, packages/inkline/src/components/IPopover/template.html, packages/inkline/src/components/ITooltip/script.js, packages/inkline/src/components/ITooltip/template.html, packages/inkline/src/css/mixins/_popup.scss, packages/inkline/src/mixins/providers/PopupProviderMixin.vue, packages/inkline/tests/components/IDropdownMenu.spec.js, packages/inkline/tests/components/ITooltip.spec.js, packages/inkline/tests/components/__snapshots__/ISelect.spec.js.snap, packages/inkline/tests/jest/setup.js, packages/inkline/tests/mixins/providers/PopupProviderMixin.spec.js, packages/nuxt-module/package-lock.json, packages/nuxt-module/tests/app/package-lock.json, packages/vue-cli-plugin/package-lock.json
#125 Upgrade Popper.js 
Upgraded dev dependencies as well.
Need some manual testing and review. Hope, all is fine :) Cause i'm never wrote tests before.
=> Feature: upgrade Popper.js

packages/docs/pages/docs/components/tabs.md, packages/inkline/src/components/ITabs/script.js, packages/inkline/src/components/ITabs/template.html
#213 Feature: title slot for i-tab component.
I have no idea how to write tests when a parent component renders slots of child components.
=> Feature: title slot for i-tab

packages/docs/pages/docs/components/tabs.md
=> doc: typos tabs

packages/docs/pages/docs/forms/validation/schema.md
s/purpopses/purposes
- ~[ ] Tests for the changes have been added (for bug fixes / features)~
Docs update
purpopses is incorrect
purposes (remove the extra `p`)
No
=> Just a typo correction

README.md
Docs update, fixes #244 
issue #244 
Compile the script without any error.
Add the correct path for the sass files.
No
=> chore: update the doc for the beta version

src/components/INavbar/__tests__/__snapshots__/index.spec.ts.snap, src/components/INavbar/template.html
Bug fix #266
The current behavior is just a div tag with the class of navbar
Semantic HTML5 nav tag for the navigation
No
=> fix: use semantic tag for the navigation (#266)

src/components/ISelect/__tests__/__snapshots__/index.spec.ts.snap, src/components/ISelect/script.ts, src/components/ISelect/template.html
Bug fix
Select arrow doesn't do anything when getting clicked.
Select arrow opens and hides the input accordingly.
=> fix: Fixed i-select caret click behaviour.

src/components/IModal/manifest.ts
~~- [ ] Tests for the changes have been added (for bug fixes / features)~~
docs update
The modal event `update:modelValue` is duplicated
There is no more duplicated events
No
=> fix: Remove duplicated modal model event

src/components/IForm/__tests__/index.spec.ts, src/components/IForm/script.ts, src/helpers/valueByPath.ts
Bug fix.
https://github.com/inkline/inkline/issues/273
The form schema is now set to `touched: true` when submitting the form in order to allow displaying errors properly.
=> fix: Setting form schema to touched on submit.

src/components/INavbar/components/INavbarCollapsible/script.ts
Bug fix
https://github.com/inkline/inkline/issues/292
The `navbar-collapsible` is now visible during SSR to prevent hydration issues.
=> fix: Fixed navbar collapsible not showing up after SSR.

src/components/INavbar/style.scss
=> bug: fix overlay tabs above navbar dropdown

.github/CONTRIBUTING.md, BACKERS.md, README.md
As I see, the main project branch is `main` now, so I updated the references also.
=> Replace 'master' with the 'main' branch references

package-lock.json, src/components/IButton/IButton.vue, src/components/IButton/__tests__/__snapshots__/index.spec.ts.snap, src/components/IButton/__tests__/index.spec.ts, src/components/IDropdown/__tests__/__snapshots__/index.spec.ts.snap, src/components/INumberInput/__tests__/__snapshots__/index.spec.ts.snap
No changes to docs, the component IButton works the same way as earlier, however the use of role= and type= is corrected behind the scenes.
Bug fix for #347. New prop type is introduced and used together with role to adhere to the usage of [Aria Button Role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) and [HTML button type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type) and [input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit)
#347 
#347 
None. …
=> I button role use

README.md
Update readme installation links.
=> feat: update README.md installation links

src/components/ICard/ICard.vue, src/components/ICard/__tests__/index.spec.ts
Feature
Render ICard component as the HTML `div` tag
add a flexibility to render ICard either as `div` or `article` tag for better semantic code support.
No
close #356
=> feat: add custom tag support for ICard component

src/components/IToastContainer/examples/basic.vue, src/components/IToastContainer/examples/color-variants.vue, src/components/IToastContainer/examples/custom.vue, src/components/IToastContainer/examples/dismissible.vue, src/components/IToastContainer/examples/duration-sticky.vue, src/components/IToastContainer/examples/duration-timed.vue, src/components/IToastContainer/examples/hide-all.vue, src/components/IToastContainer/examples/hide.vue, src/components/IToastContainer/examples/index.stories.ts, src/components/IToastContainer/examples/index.ts, src/components/IToastContainer/examples/position.vue, src/components/IToastContainer/examples/size-variants.vue, src/components/IToastContainer/examples/vnode.vue, src/plugin.ts, src/plugins/__tests__/toast.spec.ts, src/plugins/__tests__/toast.ssr.spec.ts, src/plugins/icons.ts, src/plugins/toast.ts
Feature
You would need to manually add `<IToastContainer>` to your `App.vue` component.
The plugin injects the `<IToastContainer>` automatically.
`IToastContainer` usages need to be removed.
=> feat: add toast container injection

package.json, src/components/ILayout/css/_component.scss, src/components/IModalContainer/IModalContainer.vue, src/components/IToastContainer/IToastContainer.vue, src/composables/modals/alert.ts, src/composables/modals/builder.ts, src/composables/modals/confirm.ts, src/composables/modals/prompt.ts, src/composables/useCollapsible.ts, src/composables/useModal.ts, src/composables/useToast.ts, src/constants/injectKeys.ts, src/plugins/__tests__/modal.spec.ts, src/plugins/__tests__/modal.ssr.spec.ts, src/plugins/modal.ts, src/plugins/toast.ts, src/services/__tests__/modal.spec.ts, src/services/__tests__/toast.spec.ts, src/services/index.ts, src/services/modal.ts, src/services/toast.ts, src/types/index.ts, src/types/modal.ts, src/types/toast.ts
Bug fix and feature ...
- Sidebar does not show on load when using SSR
- Toast service is not usable outside of Vue components and is not tested
- Modal service is not usable outside of Vue components and is not tested
- Sidebar now renders correctly on load when using SSR
- Toast service is usable outside of Vue components and has been moved to dedicated `services` dir
- Toast service is now at 100% test coverage
- Modal service is usable outside of Vue components and has been moved to dedicated `services` dir
- Modal service is now at 100% test coverage
What …
=> Toast and Modal Service improvements and Sidebar SSR fix

README.md
=> Update README.md images

README.md
=> Update README.md image urls

src/components/IForm/__tests__/index.spec.ts, src/types/validation.ts, src/validation/register.ts, src/validation/schema/__tests__/validateSchema.spec.ts, src/validation/schema/createSchema.ts, src/validation/schema/validateSchema.ts, src/validation/validators/__tests__/custom.spec.ts, src/validation/validators/custom.ts
Feature
Validators are synchronous.
Validators are async, therefore the `custom` validator as well as user-defined validators can contain async code.
=> feat: add support for async validators

.github/CONTRIBUTING.md, .github/workflows/auto-assign.yml, packages/cli/.np-config.json, packages/config/.np-config.json, packages/inkline/.np-config.json, packages/integrations/plugin/.np-config.json, packages/integrations/unocss/.np-config.json
=> feat: update release configuration
